version: '3.8'

services:
  your-service-name:
    build: .
    restart: always
    environment:
      - COGNITIVE_SERVICE_KEY=c847e83fd56b43eb93544e0fdd4e9d05
      - COGNITIVE_SERVICE_REGION=westeurope
      - OPENAI_API_KEY=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
      - ZEROTIER_NETWORK=159924d630e6a135
    networks:
      - external-containers
    volumes:
      - type: volume
        source: logs
        target: /app/logs

networks:
  external-containers:
    external: true

volumes:
  logs:
